apiVersion: v1
kind: ConfigMap
metadata:
  name: comment-monitor-eventmap
data:
  eventmap.yml: |
    - event_type: prombench_start
      regex_string: (?mi)^/prombench\s*(?P<RELEASE>master|v[0-9]+\.[0-9]+\.[0-9]+\S*)\s*$
      comment_template: |
        ⏱️ Welcome to Prometheus Benchmarking Tool. ⏱️

        **Compared versions:** [**`PR-{{ index . "7214" }}`**](http://{{ index . "DOMAIN_NAME" }}/{{ index . "7214" }}/prometheus-pr) and [**`{{ index . "RELEASE" }}`**](http://{{ index . "DOMAIN_NAME" }}/{{ index . "7214" }}/prometheus-release)

        After successful deployment, the benchmarking metrics can be viewed at:

        - [Prometheus Meta](http://{{ index . "prombench.rajdas.in" }}/prometheus-meta/graph?g0.expr={namespace%3D"prombench-{{ index . "7214" }}"}&g0.tab=1)
        - [Prombench Dashboard](http://{{ index . "prombench.rajdas.in" }}/grafana/d/7gmLoNDmz/prombench?orgId=1&var-pr-number={{ index . "7214" }})
        - [Grafana Explorer, Loki logs](http://{{ index . "prombench.rajdas.in" }}/grafana/explore?orgId=1&left=["now-6h","now","loki-meta",{},{"mode":"Logs"},{"ui":[true,true,true,"none"]}])

        **Other Commands:**
        To stop benchmark: `/prombench cancel`
        To restart benchmark: `/prombench restart v2.12.0`

    - event_type: prombench_stop
      regex_string: (?mi)^/prombench\s+cancel\s*$
      comment_template: |
        Benchmark cancel is in progress.

    - event_type: noop
      regex_string: (?mi)^/prombench\s*$
      comment_template: |
        Please add the version number to compare against.
        Eg. `/prombench master`, `/prombench v2.12.0`

    - event_type: prombench_restart
      regex_string: (?mi)^/prombench\s+restart\s+(?P<RELEASE>master|v[0-9]+\.[0-9]+\.[0-9]+\S*)\s*$
      comment_template: |
        ⏱️ Welcome to Prometheus Benchmarking Tool. ⏱️

        **Compared versions:** [**`PR-{{ index . "7214" }}`**](http://{{ index . "DOMAIN_NAME" }}/{{ index . "7214" }}/prometheus-pr) and [**`{{ index . "RELEASE" }}`**](http://{{ index . "DOMAIN_NAME" }}/{{ index . "7214" }}/prometheus-release)

        After successful deployment, the benchmarking metrics can be viewed at:

        - [Prometheus Meta](http://{{ index . "DOMAIN_NAME" }}/prometheus-meta/graph?g0.expr={namespace%3D"prombench-{{ index . "7214" }}"}&g0.tab=1)
        - [Prombench Dashboard](http://{{ index . "DOMAIN_NAME" }}/grafana/d/7gmLoNDmz/prombench?orgId=1&var-pr-number={{ index . "7214" }})
        - [Grafana Exlorer, Loki logs](http://{{ index . "DOMAIN_NAME" }}/grafana/explore?orgId=1&left=["now-6h","now","loki-meta",{},{"mode":"Logs"},{"ui":[true,true,true,"none"]}])

        **Other Commands:**
        To stop benchmark: `/prombench cancel`
        To restart benchmark: `/prombench restart v2.12.0`

    - event_type: funcbench_start
      regex_string: (?m)^/funcbench[[:blank:]]+(?P<BRANCH>[\w\-\/\.]+)[[:blank:]]*(?P<BENCH_FUNC_REGEX>(?:Benchmark\w*)?(?:\.\*)?)?[[:blank:]]*$
      comment_template: |
        ⏱️ Welcome to Funcbench Tool. ⏱️

        Running benchmark `{{ index . "BENCH_FUNC_REGEX"}}` on **`PR-{{ index . "7214" }}`** vs **`{{ index . "BRANCH" }}`**
