apiVersion: v1
kind: Secret
metadata:
  name: oauth-token
type: Opaque
data:
  oauth: "{{ .OAUTH_TOKEN }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: service-account
type: Opaque
data:
  service-account.json: "{{ .GKE_AUTH }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: whsecret
type: Opaque
data:
  whsecret: "{{ .WH_SECRET }}"