projectid: {{ .PROJECT_ID }}
zone: {{ .ZONE }}
cluster:
  name: {{ .CLUSTER_NAME }}
  initialclusterversion: 1.14
  nodepools:
  # GKE creates a label on every node in a pool
  # cloud.google.com/gke-nodepool: <NODEPOOL_NAME>
  # This node-pool will be used for running monitoring components
  - name: main-node
    initialnodecount: 1
    config:
      machinetype: n1-standard-2
      imagetype: COS
      disksizegb: 300
